#!/usr/bin/env bash

# Quick Test Commands for Frontend Testing Pyramid
# Run from: cd frontend/

echo "🧪 Frontend Testing Pyramid - Quick Reference"
echo "=============================================="
echo ""
echo "📋 Available Commands:"
echo ""
echo "1️⃣  Run ALL tests (Jest + E2E):"
echo "   pnpm test && pnpm test:e2e"
echo ""
echo "2️⃣  Run UNIT tests (fastest - ~1s):"
echo "   pnpm test __tests__/unit/"
echo ""
echo "3️⃣  Run COMPONENT tests (~2s):"
echo "   pnpm test __tests__/components/"
echo ""
echo "4️⃣  Run INTEGRATION tests (~1s):"
echo "   pnpm test __tests__/integration/"
echo ""
echo "5️⃣  Run E2E tests (slowest - 43s):"
echo "   pnpm test:e2e"
echo ""
echo "6️⃣  Run specific test file:"
echo "   pnpm test cn.test.ts"
echo ""
echo "7️⃣  Run tests in watch mode (auto-rerun on file changes):"
echo "   pnpm test:watch"
echo ""
echo "8️⃣  Run tests matching pattern:"
echo "   pnpm test --testNamePattern='useChatHistory'"
echo ""
echo "9️⃣  Generate coverage report:"
echo "   pnpm test --coverage"
echo ""
echo "🔟 View E2E test report:"
echo "   pnpm exec playwright show-report"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Test Statistics:"
echo "   • Unit Tests:        14 ✅"
echo "   • Component Tests:    8 ✅"
echo "   • Integration Tests:  8 ✅"
echo "   • Existing Tests:    72 ✅"
echo "   • E2E Tests:         43 ✅"
echo "   ────────────────────────"
echo "   • TOTAL:            145 ✅"
echo ""
echo "⏱️  Total Execution Time: ~54 seconds"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Development Workflow:"
echo ""
echo "   1. Make code changes"
echo "   2. Run: pnpm test:watch"
echo "   3. Tests auto-run on save"
echo "   4. Fix any failures"
echo "   5. Commit when all green"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Documentation:"
echo "   • See __tests__/README.md for detailed test structure"
echo "   • See TESTING.md for comprehensive test overview"
echo ""
