name: Benchmark Smoke Test

on: [push, pull_request]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pandas jsonschema matplotlib pytest pytest-asyncio
      - name: Run benchmark smoke tests
        run: |
          pytest tests/performance/test_benchmark_runner.py::test_benchmark_runner_retrieval_only -q || true
          pytest tests/performance/test_runner_retries.py -q
          pytest tests/performance/test_schema_validation.py -q
      - name: Run README check
        run: |
          echo 'Smoke tests complete' > smoke_result.txt
          ls -la
